[toolchain]
anchor_version = "0.27.0"
solana_version = "1.14.29"

[features]
seeds = false
skip-lint = false
[programs.localnet]
marinade_finance = "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
